version: '3'

services:
  was:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: was
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL= ${DATABASE_URL}
      - DATABASE_ID= ${DATABASE_ID}
      - DATABASE_PASSWORD= ${DATABASE_PASSWORD}
      - REDIS_HOST= ${REDIS_HOST}
      - REDIS_PORT= ${REDIS_PORT}
      - REDIS_PASSWORD= ${REDIS_PASSWORD}
      - JWT_SECRET_KEY= ${JWT_SECRET_KEY}
      - STATE_SECRET_KEY= ${STATE_SECRET_KEY}