spring:
  output:
    ansi:
      enabled: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: "${DATABASE_URL}"
    driver-class-name: org.mariadb.jdbc.Driver
    username: "${DATABASE_ID}"
    password: "${DATABASE_PASSWORD}"

  jpa:
    open-in-view: false
    show-sql: true

  redis:
    host: "${REDIS_HOST}"
    port: "${REDIS_PORT}"
    password: "${REDIS_PASSWORD}"

  jwt:
    secret-key: "${JWT_SECRET_KEY}"
  state:
    secret-key: "${STATE_SECRET_KEY}"

springdoc:
  packages-to-scan: com.salary
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    disable-swagger-default-url: true
    path: /api-docs.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true